# Site settings
title: Nick-G Software Development
description: The official website of Nick-G Software Development.
baseurl: "/jekyll-bootstrap" # the subpath of your site, e.g. /blog
url: "https://nick-g.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# SASS
sass:
  style: :compressed

# Defaults
defaults:
  - scope:
      path: "*"
    values:
      layout: default

# Exclude
exclude:
  - assets/js/bootstrap.bundle.min.js
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .sass-cache/
  - .jekyll-cache/
