- title: ngimbel64.github.io
  description: Official website utilizing Jekyll static webpages with Tailwind CSS, daisy UI, and GSAP for animations.
  url: https://github.com/ngimb64/ngimb64.github.io

- title: Reactive File Transfer
  description: RFT establishes an automated multi-directional encrypted file transfer service between two systems.
  url: https://github.com/ngimb64/Reactive-File-Transfer

- title: Crypt Drive
  description: Creates a local client to facilitate password-protected encrypted Google Drive uploads and methods of secure key sharing.
  url: https://github.com/ngimb64/Crypt-Drive

- title: Virus Total PyClient
  description: Provides a CLI and GUI application that acts as a local client to automate checking files through the Virus Total API.
  url: https://github.com/ngimb64/Virus-Total-PyClient

- title: Bandwidth SpeedTester
  description: Automates checking connection bandwidth in a single or series of tests, while enabling the user to create a time series graph to visualize test results.
  url: https://github.com/ngimb64/Bandwidth-SpeedTester

- title: File Database
  description: Local database for storing and managing files.
  url: https://github.com/ngimb64/File-Database

- title: AutoFile Organizer
  description: Automates moving files in a monitored source folder to various destination folders based on the file extension.
  url: https://github.com/ngimb64/AutoFile-Organizer

- title: Backup Buddy
  description: Backs up folder contents to destination location in file systems, with recursive capabilities.
  url: https://github.com/ngimb64/Backup-Buddy

- title: Mp3Py
  description: Multi-threaded command line music player tied to directional key listeners to control execution.
  url: https://github.com/ngimb64/Mp3Py

- title: Tutorial Assistant
  description: Designed to help making tutorials associated with command line such as Linux or Cisco. Automates gathering screenshots and logs sentences to parse and log to output file.
  url: https://github.com/ngimb64/Tutorial-Assistant

- title: Screenshot Assistant
  description: Handy tool to automate gathering screenshots. Gathers screenshots of the default interval of every 5 seconds unless modified.
  url: https://github.com/ngimb64/Screenshot-Assistant

- title: Subnet Calculator
  description: Checks if the two entered IP addresses are on the same subnet.
  url: https://github.com/ngimb64/Subnet-Calculator

- title: Networking Tutorials
  description: Hands on packet tracer network configuration practicals made for cybr.com tutorials.
  url: https://github.com/ngimb64/Networking-Tutorials

- title: Learning Projects
  description: https://github.com/ngimb64/Learning-Projects
  url: A handful of programs back from when I just started learning Python.

- title: MySQL DbBuild
  description: Automate database building based off data imported from module files.
  url: https://github.com/ngimb64/MySQL-DbBuild
